apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: jenkins 
  name: jenkins
spec:
  replicas: 1
  selector:
    name: jenkins
  template:
    metadata:
      labels:
        name: jenkins
    spec:
      volumes:
      - name: jenkins-home
        awsElasticBlockStore:
          volumeID: vol-a4f6db65
          fsType: ext4
      containers:
      - name: jenkins
        resources:
          limits:
            cpu: 1
            memory: "512Mi"
        image: loky9000/jenkins
        ports:
          - containerPort: 8080
            name: jenkins
        volumeMounts:
        - name: jenkins-home
          mountPath: /var/jenkins_home
