apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    name: nginx
spec:
  containers:
    - command:
            - /run.sh
      resources:
        limits:
          cpu: 0.2
      env:
        - name: BACKEND_SERVICE_HOST
          value: $(TOMCAT_SERVICE_HOST)
        - name: BACKEND_SERVICE_PORT
          value: $(TOMCAT_SERVICE_PORT)
        - name: SERVER_NAME
          value: kube-test-lb-1648772719.us-east-1.elb.amazonaws.com
      image: loky9000/nginx
      name: nginx
      ports:
        - containerPort: 80
          name: nginx