apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: nginx-x
  name: nginx
spec:
  replicas: 1
  selector:
    name: nginx
  template:
    metadata:
      labels:
        name: nginx
    spec:
      containers:
       - command:
         - /run.sh
         resources:
           limits:
             cpu: 0.2
         env:
         - name: BACKEND_SERVICE_HOST
           value: $(TOMCAT_SERVICE_HOST)
         - name: BACKEND_SERVICE_PORT
           value: $(TOMCAT_SERVICE_PORT)
         - name: SERVER_NAME
           value: kube-lb-tonomi.com
         image: loky9000/nginx
         name: nginx
         ports:
         - containerPort: 80
           name: nginx
