apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: tomcat
  name: tomcat
spec:
  replicas: 1
  selector:
    name: tomcat
  template:
    metadata:
      labels:
        name: tomcat
    spec:
      volumes:
      - name: builder-storage
        emptyDir: {}
      containers:
      - name: builder
        image: qubell/artifact-builder:latest
        ports:
        - containerPort: 80
          name: builder
        command:
        - /run.sh
        resources:
          limits:
            cpu: 0.1
            memory: "300Mi"
        env:
        - name: GIT_URL
          value: "https://github.com/qubell/starter-java-web.git"
        - name: GIT_BRANCH
          value: "red"
        - name: PUBLISH_PATH
          value: "petclinic.war"
        - name: ARTIFACT_PATTERN
          value: "*.war"
        volumeMounts:
        - name: builder-storage
          mountPath: /source
      - name: tomcat
        image: loky9000/tomcat:latest
        ports:
        - containerPort: 8080
          name: tomcat
        command:
        - /configure_and_run.sh
        resources:
          limits:
            cpu: 0.3
            memory: "300Mi"
        env:
        - name: WAR_URL
          value: file:///source/petclinic.war
        - name: MYSQL_HOST
          value: $(MYSQL_SERVICE_HOST)
        - name: MYSQL_PORT
          value: $(MYSQL_SERVICE_PORT)
        - name: MYSQL_USERNAME
          value: petclinic
        - name: MYSQL_PASSWORD
          value: petclinic
        volumeMounts:
        - name: builder-storage
          mountPath: /source
